import { type RouteConfig, index, route , } from "@react-router/dev/routes";

export default [
    // index("routes/home.tsx"),
    route("/", "routes/home.tsx"),
    route("/services", "routes/Services.tsx"),
    route("/about", "routes/About.tsx"),
    route("/mycrud", "routes/MyCrud.tsx"),
    route("/details/:type/:id", "routes/MovieDetailPage.tsx"),
    route("/auth/callback", "routes/auth/callback.tsx"),
    route("*", "routes/Error.tsx"),

] satisfies RouteConfig;
// This file is automatically generated. Do not edit this file directly.